# Generated by Django 2.1.4 on 2019-01-31 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usr_name', models.CharField(max_length=250)),
                ('passwd', models.CharField(max_length=250)),
                ('server_addr', models.CharField(max_length=250)),
                ('conn_type', models.CharField(max_length=50)),
                ('db_name', models.CharField(max_length=250)),
            ],
        ),
    ]
